POST http://localhost:4001/register HTTP/1.1
Content-Type: application/json


{
    "name": "testuser1",
    "email": "testuser1@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:4001/login HTTP/1.1
Content-Type: application/json

{
    "email" : "testuser1@gmail.com",
    "password": "12345678"
}

###

GET http://localhost:4001/movies?page=1 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:4001/moviesfilter?uuid=1 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:4001/moviesfilter?title=BatMan HTTP/1.1
Content-Type: application/json

